services:
  rabbit:
    build:
      context: .
      dockerfile: Dockerfile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
    ports:
      - ${RABBITMQ_PORT_APP_CONNECTION}:5672
      - ${RABBITMQ_PORT_DASHBOARD}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - data:/var/lib/rabbitmq
      - logs:/var/log/rabbitmq
volumes:
  data:
    external: true
    name: ${VOLUME_RABBIT_DATA}
  logs:
    external: true
    name: ${VOLUME_RABBIT_LOG}
