services:
  rabbit:
    build:
      context: ./dockerfile
      dockerfile: rabbit-dockerfile
    ports:
      - ${RABBITMQ_PORT_APP_CONNECTION}:5672
      - ${RABBITMQ_PORT_DASHBOARD}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - data:/var/lib/rabbitmq
      - logs:/var/log/rabbitmq

  php-apache:
    image: php:7.2-apache
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - rabbit

volumes:
  data:
    external: true
    name: ${VOLUME_RABBIT_DATA}
  logs:
    external: true
    name: ${VOLUME_RABBIT_LOG}
